<?php 
   
///////// OLD
	/* $group_name = $this->formText('group_name','',array('class'=>'txtmedium'));
	$avatar = $this->formFile('avatar',array('style'=>'width: 250px'));
	$ranking = $this->formFile('ranking',array('style'=>'width: 250px'));
	$options = array('No','Yes');
	$group_acp = $this->formRadio('group_acp',0,null,$options, ' ');
	$group_default = $this->formRadio('group_default',0,null,$options, ' ');
	$options = array('Inactive','Active');
	$status = $this->formRadio('status',0,null,$options, ' ');
	$order = $this->formText('order',10,array('class'=>'txtshort')); */
	
    //-------------------INPUT ELEMENTS----------------
    $name 		    = $this->formText('name',$this->Items['name'],array('class'=>'txtmedium'));
    $picture 	    = $this->formFile('picture');
    $price			= $this->formText('price',$this->Items['price'],array('class'=>'txtmedium'));
    $selloff    	= $this->formText('selloff',$this->Items['selloff'],array('class'=>'txtmedium'));
    $order		    = $this->formText('order',$this->Items['order'],array('class'=>'txtmedium'));
    
    
    $options		= array('Inactive','Active');
    $status			= $this->formRadio('status','',null,$options, ' ');
    $special		= $this->formRadio('special','',null,$options, ' ');
    
    $category 		= $this->cmsSelect('category',null,
                                                            $this->slbCategory,array('size'=>10,'style'=>'min-width: 200px;'));
    
    /* $options = $this->selectboxgroup;
    
    $slbGroup = $this->formSelect('group_id',$this->Items['group_id'],array('style'=>"min-width: 200px"),$options);*/
    //$sign = $this->cmsReplaceString($this->Item['sign']); 
    
    //$sign = $this->cmsEditor('sign',$sign,array('toolbar'=>'Default','language'=>'vi'));
    //echo $this->Item['sign'];
    $arrInput = array(
        array('label'=>'Sport Name: ', 'input'=>$name),
        array('label'=>'Picture: ', 'input'=>$picture),
        array('label'=>'Price: ', 'input'=>$price),
        array('label'=>'SellOff: ', 'input'=>$selloff),
        array('label'=>'Order: ', 'input'=>$order),
        array('label'=>'Status: ', 'input'=>$status),
        array('label'=>'Special: ', 'input'=>$special),
        array('label'=>'Category: ', 'input'=>$category),
        
    );
    //------------------------MESSAGES ERROR----------------------
    $errors = '';
    if(count($this->messageError)>0){
        $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
    }
	
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


        <?php echo $this->render('admin-product/toolbar/add.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('admin-product/submenu/index.php') ?>
                <?php echo $errors?>
                
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                        
                            <div id="adminfieldset">
                                <div class="adminheader">Detail</div>
                             
								<?php echo $this->partialLoop('rowadd.php',$arrInput);?>
                                
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>