<?php //$linkInfo = $this->baseUrl($this->currentControlle.'/info/id/'.$id)
    
    $ssfilter = $this->arrParam['sessionfilter'];
    echo "<pre>";
    print_r($ssfilter);
    echo "</pre>";
    
    // Phan sap xep cua cac nhan                                                    
    $actionLink = $this->baseUrl($this->currentControlle.'/filter/type/order');     
    
    $keyaftersearch = $ssfilter['searchproduct'];
    $keysearch  = $this->formText('searchbox',$keyaftersearch,array('class'=>'txtsearch'));
    
    // Tìm Kiếm
    $linksearch = $this->baseUrl($this->currentControlle.'/filter/type/search/key/1');
    $btnsearch  = $this->formButton('search-button','Tìm Kiếm',array('onclick'=>"OnSubmitForm('". $linksearch ."')"));
    
    // Xóa Tìm kiếm
    $linkclearsearch = $this->baseUrl($this->currentControlle.'/filter/type/search/key/0');
    $btnclearsearch  = $this->formButton('clear-button','Xóa tìm kiếm',array('onclick'=>"OnSubmitForm('". $linkclearsearch ."')"));
 
?>
<form name="appForm" method="post" action="">

        <?php echo $this->render('admin-product/toolbar/index.php') ?>
                        <div class="clr"></div>
                                                                                                            
                <?php echo $this->render('admin-product/submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                                <div id="search">
                                    <div style="float:left">
                                        <?php echo $keysearch . ' ' . $btnsearch . ' ' .$btnclearsearch;?>
                                    </div>
                                    <div style="float:right">
                                        
                                    </div>
                                      <div class="clr"></div>
                                </div>
                                
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()"></th>
                                            <th width="300"> Sport Name </th>
                                            <th> Picture </th>
                                            <th> Price </th>
                                            <th> Sellof </th>
                                            <th width="89">Status</th>
                                            <th width="89">Special</th>
                                            <th width="83">Order</th>
                                            <th width="100">created_by</th>						
                                            <th width="100">Categoryname</th>
                                            <th width="120">Control</th>

                                            <th width="34"> ID </th>
                                        </tr>
                                    </thead>
                                    <?php 
                                    
                                    
                                        foreach ($this->Items as $key=>$value){
                                        //var_dump(123);exit;
                                        
                                        $productname    = $value['name'];
                                        //$picture        = '';
                                        if(!empty($value['picture'])){
                                            $picture 	= FILE_URL.'/products/img100x100/'.$value['picture'];
                                            $picturesau = '<img src="'.$picture.'"> <br>'.$value['picture'];
                                        }
                                        $price          = $value['price'];
                                        $selloff        = $value['selloff'];
                                        
                                        $status         = $value['status'];                                                                               
                                        $special        = $value['special'];
                                        
                                        $order          = $this->formText('order['.$value['id'].']',$value['order'],array('style'=>'width: 30px; text-align: center;'));
                                        $created_by     = $value['created_boi'];
                                        $categoryname   = $value['catename'];
                                        $id             = $value['id'];
                                        if ($status == 1){
                                            $linkstatus =  $this->baseUrl($this->currentControlle.'/status/type/0/id/'.$id);
                                            $status = '<img src="'.$this->ImageURL.'/icon/active.png">';
                                        }else{
                                            $linkstatus =  $this->baseUrl($this->currentControlle.'/status/type/1/id/'.$id);
                                            $status = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
                                        }
                                         if ($special == 1){
                                            $linkspecial    =  $this->baseUrl($this->currentControlle.'/status/type/0/idspc/'.$id);
                                            $special = '<img src="'.$this->ImageURL.'/icon/active.png">';
                                        }else{
                                            $linkspecial    =  $this->baseUrl($this->currentControlle.'/status/type/1/idspc/'.$id);
                                            $special = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
                                        }
                                        $linkinfogroup      = $this->baseUrl($this->currentControlle.'/info/id/'.$id);
                                        $linkEditGroup      = $this->baseUrl($this->currentControlle.'/edit/id/'.$id);
                                        $linkDeleteGroup    = $this->baseUrl($this->currentControlle.'/delete/id/'.$id);
                                        $checkbox           = $this->formCheckbox('cid[]',$id);
                                        
                                        
                                    ?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $checkbox;?></td>
                                        <td align="left"><?php  echo $productname;?></td>
                                        <td align="center">
                                        <?php echo $picturesau;?>
                                        </td>
                                        <td align="center"><?php echo $price;?></td>
                                        <td align="center"><?php echo $selloff;?></td>
                                        <td align="center">
                                            <a href="<?php echo $linkstatus;?>">
                                        	   <?php echo $status;?>
                                            </a>
                                        </td>
                                        <td align="center">
                                            <a href="<?php echo $linkspecial;?>">
                                        	   <?php echo $special;?>
                                            </a>
                                        </td>
                                         <td align="center"><?php echo $order;?></td>
                                         <td align="center"><?php echo $created_by;?></td>

                                        <td align="center"><?php echo $categoryname;?></td>
                                        <td align="center">
                                        <a href="<?php echo $linkinfogroup;?>">
                                        	<img src="<?php echo $this->ImageURL?>/icon_info.png" title="View Info"> 
                                        </a>
                                        <a href="<?php echo $linkEditGroup;?>">
                                            <img src="<?php echo $this->ImageURL?>/icon_edit.png" title="Edit Group"> 
                                        </a>
                                        <a href="<?php echo $linkDeleteGroup;?>">
                                            <img src="<?php echo $this->ImageURL?>/icon_del.png" title="Delete Group"> 
                                         </a></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
                                        }
                                            
                                            ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                       <?php 
                                                          $currentUrl = $this->baseUrl($this->currentControlle . '/index');
                                                          echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                       ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>