<?php 
   
///////// OLD
	/* $group_name = $this->formText('group_name','',array('class'=>'txtmedium'));
	$avatar = $this->formFile('avatar',array('style'=>'width: 250px'));
	$ranking = $this->formFile('ranking',array('style'=>'width: 250px'));
	$options = array('No','Yes');
	$group_acp = $this->formRadio('group_acp',0,null,$options, ' ');
	$group_default = $this->formRadio('group_default',0,null,$options, ' ');
	$options = array('Inactive','Active');
	$status = $this->formRadio('status',0,null,$options, ' ');
	$order = $this->formText('order',10,array('class'=>'txtshort')); */
	
    //-------------------INPUT ELEMENTS----------------
    $name 		    = $this->Items['name'];
    if(!empty($this->Items['picture'])){
        $picture 	= FILE_URL.'/products/img100x100/'.$this->Items['picture'];
        $picturesau    = '<img src="'.$picture.'"> <br>'.$this->Items['picture'];
    }
    //$picture 	    = $this->formFile('picture');
    $price			= $this->Items['price'];
    $selloff    	= $this->Items['selloff'];
    $order		    = $this->Items['order'];
    $status			= $this->Items['status'];
    if ($status == 1){
        $status = '<img src="'.$this->ImageURL.'/icon/active.png">';
    }else{
        $status = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
    }
    $special		= $this->Items['special'];
    if ($special == 1){
        $special = '<img src="'.$this->ImageURL.'/icon/active.png">';
    }else{
        $special = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
    }
       
    $category 		= $this->Items['catename'];
    
    /* $options = $this->selectboxgroup;
    
    $slbGroup = $this->formSelect('group_id',$this->Items['group_id'],array('style'=>"min-width: 200px"),$options);*/
    //$sign = $this->cmsReplaceString($this->Item['sign']); 
    
    //$sign = $this->cmsEditor('sign',$sign,array('toolbar'=>'Default','language'=>'vi'));
    //echo $this->Item['sign'];
    $arrInput = array(
        array('label'=>'Sport Name: ', 'input'=>$name),
        array('label'=>'Picture: ', 'input'=>$picturesau,'style'=>'margin-left: 175px;'),
        array('label'=>'Price: ', 'input'=>$price),
        array('label'=>'SellOff: ', 'input'=>$selloff),
        array('label'=>'Order: ', 'input'=>$order),
        array('label'=>'Status: ', 'input'=>$status),
        array('label'=>'Special: ', 'input'=>$special),
        array('label'=>'Category: ', 'input'=>$category),
        
    );
    //------------------------MESSAGES ERROR----------------------
    $errors = '';
    if(count($this->messageError)>0){
        $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
    }
	
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


        <?php echo $this->render('admin-product/toolbar/add.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('admin-product/submenu/index.php') ?>
                <?php echo $errors?>
                
                
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                        
                            <div id="adminfieldset">
                                <div class="adminheader">Detail</div>
                             
								<?php echo $this->partialLoop('rowadd.php',$arrInput);?>
                                
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>