<?php 
	$group_name    = $this->Item['group_name'];
	$avatar        = $this->Item['avatar'];
	$ranking       = $this->Item['ranking'];
	
	$group_acp     = $this->Item['group_acp'];
	$group_default = $this->Item['group_default'];
	
	$created       = $this->Item['created'];
	$created_by    = $this->Item['created_by'];
	
	$modified      = $this->Item['modified'];
	$modifiedby    = $this->Item['modified_by'];
	
	$status        = $this->Item['status'];
	$order         = $this->Item['order'];
?>
<form name="appForm" method="post" action="">

        <?php echo $this->render('toolbar/delete.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->

<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div class="error">
								    Do you agree to delete this Item
								</div>
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>