<?php 
	$group_name = $this->formText('group_name',$this->Item['group_name'],array('class'=>'txtmedium'));
	$avatar = $this->formFile('avatar',array('style'=>'width: 250px'));
	$ranking = $this->formFile('ranking',array('style'=>'width: 250px'));
	$options = array('No','Yes');
	$group_acp = $this->formRadio('group_acp',$this->Item['group_acp'],null,$options, ' ');
	$group_default = $this->formRadio('group_default',$this->Item['group_default'],null,$options, ' ');
	$options = array('Inactive','Active');
	$status = $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	$order = $this->formText('order',$this->Item['order'],array('class'=>'txtshort'));
?>
<form name="appForm" method="post" action="">

        <?php echo $this->render('toolbar/edit.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->

<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div id="row">
                                    <div class="label">Group name:</div>
                                    <?php echo $group_name;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Avatar:</div>
                                    <?php echo $avatar;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Ranking:</div>
                                    <?php echo $ranking;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Admin Control Panel:</div>
                                    <?php echo $group_acp;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Group default:</div>
                                    <?php echo $group_default;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Ordering:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>