<form name="appForm" method="post" action="">

        <?php echo $this->render('toolbar/index.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->


                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox"></th>
                                            <th>Group name</th>
                                            <th width="89">Status</th>
                                            <th width="83">ACP</th>
                                            <th width="86">Order</th>						
                                            <th width="77">Member</th>
                                            <th width="90">Control</th>

                                            <th width="34">ID</th>
                                        </tr>
                                    </thead>
                                    <?php foreach ($this->Items as $key=>$value){
                                        $groupname = $value['group_name'];
                                        $status    = $value['status'];
                                        $groupacp  = $value['group_acp'];
                                        $order     = $this->formText('order',$value['order'],array('style'=>'width: 30px; text-align: center;'));
                                        $id        = $value['id'];
                                    ?>
                                    <tr class="even">						
                                        <td align="center"><input type="checkbox" name="checkbox2" id="checkbox2"></td>
                                        <td align="left"><?php echo $groupname;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $groupacp;?></td>
                                        <td align="center">
                                        <?php echo $order;?>
                                        </td>

                                        <td align="center">3</td>
                                        <td align="center">
                                        <a href="#">
                                        	<img src="<?php echo $this->ImageURL?>/icon_info.png" width="16" height="16"> 
                                        </a>
                                        <a href="#">
                                            <img src="<?php echo $this->ImageURL?>/icon_edit.png" width="16" height="16"> 
                                        </a>
                                        <a href="#">
                                            <img src="<?php echo $this->ImageURL?>/icon_del.png" width="16" height="16"> 
                                         </a></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php }?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <div class="limit">Display #
                                                            <select onchange="submitform();" size="1" class="inputbox" id="limit" name="limit">
                                                                <option value="5">5</option></select>
                                                        </div>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>