<?php //$linkInfo = $this->baseUrl($this->currentControlle.'/info/id/'.$id)
  
    /* echo "<pre>";
    print_r($this->arrParam);
    echo "</pre>"; */
    $ssfilter = $this->arrParam['sessionfilter'];
    echo "<pre>";
    print_r($ssfilter);
    echo "</pre>";
    
    
    // Phan sap xep cua cac nhan
    $actionLink = $this->baseUrl($this->currentControlle.'/filter/type/order');
    
    $lblID 	= $this->cmsLinkSort('ID','g.id',$ssfilter,
        $this->ImageURL . '/icon',$actionLink);
    
    $lblMember	= $this->cmsLinkSort('Member','members',$ssfilter,
        $this->ImageURL . '/icon',$actionLink);
    
    // Key sau khi tim kiem, neu khong co se rong
    $keyaftersearch = $ssfilter['searchbox'];
    $keysearch  = $this->formText('searchbox',$keyaftersearch,array('class'=>'txtsearch'));
    
    // Tìm Kiếm
    $linksearch = $this->baseUrl($this->currentControlle.'/filter/type/search/key/1');
    $btnsearch  = $this->formButton('search-button','Tìm Kiếm',array('onclick'=>"OnSubmitForm('". $linksearch ."')"));
    
    // Xóa Tìm kiếm
    $linkclearsearch = $this->baseUrl($this->currentControlle.'/filter/type/search/key/0');
    $btnclearsearch  = $this->formButton('clear-button','Xóa tìm kiếm',array('onclick'=>"OnSubmitForm('". $linkclearsearch ."')"));
    
    // Sap xep
     
    if($ssfilter['col'] != 'g.group_name'){
        $linkOder =  $this->baseUrl($this->currentControlle . '/filter/type/order/col/g.group_name/by/DESC');
        $iconSort = $this->ImageURL . '/icon/arrow_down.png';
    }else{
        if($ssfilter['order'] == 'DESC'){ 
            $by = 'ASC';
            $iconSort = $this->ImageURL . '/icon/arrow_down.png';
        }else{
            $by = 'DESC';
            $iconSort = $this->ImageURL. '/icon/arrow_up.png';
        }
    
        $linkOder =  $this->baseUrl($this->currentControlle .
            '/filter/type/order/col/g.group_name/by/' . $by);
    }
    
    
?>
<form name="appForm" method="post" action="">
        
        <?php  echo $this->render('toolbar/index.php') ?>
                        <div class="clr"></div>
                
                <?php echo $this->render('submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                                <div id="search">
                                    <div>
                                        <?php echo $keysearch . ' ' . $btnsearch . ' ' .$btnclearsearch;?>
                                    </div>
                                </div>
                                
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()"></th>
                                            <th>
                                                <a href="<?php echo $linkOder;?>">Group Name</a>
                                                <br>
                                            	<img src="<?php echo $iconSort;?>">
                                            </th>
                                            <th width="89">Status</th>
                                            <th width="83">ACP</th>
                                            <th width="86">Order</th>						
                                            <th width="77"><?php echo $lblMember;?></th>
                                            <th width="90">Control</th>

                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
                                    <?php foreach ($this->Items as $key=>$value){
                                        $groupname = $value['group_name'];
                                        $status    = $value['status'];
                                        $groupacp  = $value['group_acp'];
                                        $order     = $this->formText('order['.$value['id'].']',$value['order'],array('style'=>'width: 30px; text-align: center;'));
                                        $member    = $value['members'];
                                        $id        = $value['id'];
                                        if ($status == 1){
                                            $linkstatus =  $this->baseUrl($this->currentControlle.'/status/type/0/id/'.$id);
                                            $status = '<img src="'.$this->ImageURL.'/icon/active.png">';
                                        }else{
                                            $linkstatus =  $this->baseUrl($this->currentControlle.'/status/type/1/id/'.$id);
                                            $status = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
                                        }
                                        if ($groupacp == 1){
                                            $linkgroupacp =  $this->baseUrl($this->currentControlle.'/status/type/0/idacp/'.$id);
                                            $groupacp = '<img src="'.$this->ImageURL.'/icon/active.png">';
                                        }else{
                                            $linkgroupacp =  $this->baseUrl($this->currentControlle.'/status/type/1/idacp/'.$id);
                                            $groupacp = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
                                        }
                                        $linkinfogroup      = $this->baseUrl($this->currentControlle.'/info/id/'.$id);
                                        $linkEditGroup      = $this->baseUrl($this->currentControlle.'/edit/id/'.$id);
                                        $linkDeleteGroup    = $this->baseUrl($this->currentControlle.'/delete/id/'.$id);
                                        $checkbox           = $this->formCheckbox('cid[]',$id);
                                        
                                    ?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $checkbox;?></td>
                                        <td align="left"><?php  echo $groupname;?></td>
                                        <td align="center">
                                            <a href="<?php echo $linkstatus;?>">
                                        	   <?php echo $status;?>
                                            </a>
                                        </td>
                                        <td align="center">
                                            <a href="<?php echo $linkgroupacp;?>">
                                        	   <?php echo $groupacp;?>
                                            </a>
                                        </td>
                                        
                                        <td align="center">
                                        <?php echo $order;?>
                                        </td>

                                        <td align="center"><?php echo $member;?></td>
                                        <td align="center">
                                        <a href="<?php echo $linkinfogroup;?>">
                                        	<img src="<?php echo $this->ImageURL?>/icon_info.png" title="View Info"> 
                                        </a>
                                        <a href="<?php echo $linkEditGroup;?>">
                                            <img src="<?php echo $this->ImageURL?>/icon_edit.png" title="Edit Group"> 
                                        </a>
                                        <a href="<?php echo $linkDeleteGroup;?>">
                                            <img src="<?php echo $this->ImageURL?>/icon_del.png" title="Delete Group"> 
                                         </a></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php }?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                       <?php 
                                                           $currentUrl = $this->baseUrl($this->currentControlle . '/index');
                                                           echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                       ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>