<?php 
	$group_name    = $this->Item['group_name'];
	$avatar        = $this->Item['avatar'];                            // Null In Database
	$ranking       = $this->Item['ranking'];                           // Null In Database
	
	$group_acp     = $this->Item['group_acp'];
	$group_default = $this->Item['group_default'];
	
	$created       = $this->Item['created'];
	$created_by    = $this->Item['created_by'];
	
	$modified      = $this->Item['modified'];
	$modifiedby    = $this->Item['modified_by'];
	
	$status        = $this->Item['status'];
	$order         = $this->Item['order'];
?>
<form name="appForm" method="post" action="">

        <?php echo $this->render('toolbar/info.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->

<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div id="row">
                                    <div class="label">Group name:</div>
                                    <?php echo $group_name;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Avatar:</div>
                                    <?php echo $avatar;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Ranking:</div>
                                    <?php echo $ranking;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Admin Control Panel:</div>
                                    <?php echo $group_acp;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Group default:</div>
                                    <?php echo $group_default;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Created:</div>
                                    <?php echo $created;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Created_by:</div>
                                    <?php echo $created_by;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Modified:</div>
                                    <?php echo $modified;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Modified_by:</div>
                                    <?php echo $modifiedby;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                
                                 <div id="row">
                                    <div class="label">Ordering:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>