<!DOCTYPE html>
<html>

<!-- Mirrored from demo.harnishdesign.net/html/bigshop/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 13 Aug 2015 08:26:01 GMT -->
<head>
<?php echo $this->headTitle()?>
<link href="<?php echo $this->ImageURL;?>/favicon.png" rel="icon" />
<?php echo $this->headMeta()?>
<!-- CSS Part Start-->
<?php echo TEMPLATE_PATH;?>
<?php echo $this->headLink()?>
<!-- CSS Part End-->
<!-- JS Part Start-->
<script type="text/javascript" src="/zendmulty/public/templates/public/sports/js/colorbox/jquery.colorbox-min.js"></script>

<?php echo $this->headScript()?>
<!-- JS Part End-->
</head>
<body>
<div class="main-wrapper">
  <!-- Header Parts Start-->
  <?php echo $this->render('html/header.php')?>  <!--Top Navigation Start-->
  <div id="menu"><span>Menu</span>
    <ul>
      <li class="home"><a  title="Home" href="index-2.html"><span>Home</span></a></li>
      <li><a href="category.html">Electronics</a>
        <div>
          <ul>
            <li><a href="category.html">Cameras</a></li>
            <li><a href="category.html">Phones</a></li>
            <li><a href="category.html">Tablets</a></li>
          </ul>
        </div>
      </li>
      <li><a href="category.html">Accessories</a> </li>
      <li><a href="category.html">Shoes</a>
        <div>
          <ul>
            <li><a href="category.html">Casual shoes</a></li>
            <li><a href="category.html">Fancy shoes</a></li>
            <li><a href="category.html">Sports shoes</a></li>
          </ul>
        </div>
      </li>
      <li><a href="category.html">Books</a>
        <div>
          <ul>
            <li><a href="category.html">Audio Books</a></li>
            <li><a href="category.html">Comedy Book</a></li>
            <li><a href="category.html">Comics Books</a></li>
            <li><a href="category.html">Computer Book</a></li>
            <li><a href="category.html">Cookies Books</a></li>
          </ul>
          <ul>
            <li><a href="category.html">English Books</a></li>
            <li><a href="category.html">Fashion Books</a></li>
            <li><a href="category.html">Games Books</a></li>
            <li><a href="category.html">God Books</a></li>
            <li><a href="category.html">Journal Book</a></li>
          </ul>
          <ul>
            <li><a href="category.html">Knowledge Books</a></li>
            <li><a href="category.html">Magic Books</a></li>
            <li><a href="category.html">Management Books</a></li>
            <li><a href="category.html">Student Books</a></li>
            <li><a href="category.html">Teachers Books</a></li>
          </ul>
          <ul>
            <li><a href="category.html">Toys Books</a></li>
            <li><a href="category.html">Travel Books</a></li>
            <li><a href="category.html">Video Books</a></li>
          </ul>
        </div>
      </li>
      <li><a href="category.html">Clothing</a>
        <div>
          <ul>
            <li><a href="category.html">Women Clothing</a></li>
            <li><a href="category.html">Men Clothing</a></li>
          </ul>
        </div>
      </li>
      <li><a href="category.html">Furniture</a> </li>
      <li><a href="category.html">Beauty &amp; Health Care</a> </li>
    </ul>
  </div>
  <!--Top Navigation Start-->
  <div id="container">
    <!--Left Part-->
    <div id="column-left">
      <!--Categories Part Start-->
      <div class="box">
        <div class="box-heading">Categories</div>
        <div class="box-content box-category">
          <ul id="custom_accordion">
            <li class="category25"><a class="cuuchild " href="category.html">Electronics</a> <span class="down"></span>
              <ul>
                <li class="category30"><a class="nochild " href="category.html">Cameras</a></li>
                <li class="category29"><a class="nochild " href="category.html">Phones</a></li>
                <li class="category28"><a class="cuuchild " href="category.html">Tablets</a> <span class="down"></span>
                  <ul>
                    <li class="category35"><a class="nochild " href="category.html">test 1</a></li>
                    <li class="category36"><a class="nochild " href="category.html">test 2</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li class="category57"><a class="nochild " href="category.html">Accessories</a></li>
            <li class="category18"><a class="cuuchild " href="category.html">Shoes</a> <span class="down"></span>
              <ul>
                <li class="category46"><a class="nochild " href="category.html">Casual shoes</a></li>
                <li class="category45"><a class="nochild " href="category.html">Fancy shoes</a></li>
                <li><a class="nochild " href="category.html">Sports shoes</a></li>
              </ul>
            </li>
            <li><a class="cuuchild " href="category.html">Clothing</a> <span class="down"></span>
              <ul>
                <li><a class="nochild " href="category.html">Women Clothing</a></li>
                <li><a class="nochild " href="category.html">Men Clothing</a></li>
              </ul>
            </li>
            <li><a class="nochild " href="category.html">Furniture</a></li>
            <li><a class="nochild " href="category.html">Beauty &amp; Health Care</a></li>
            <li><a class="cuuchild " href="category.html">Books</a> <span class="down"></span>
              <ul>
                <li><a class="nochild " href="category.html">Audio Books</a></li>
                <li><a class="nochild " href="category.html">Comedy Book</a></li>
                <li><a class="nochild " href="category.html">Comics Books</a></li>
                <li><a class="nochild " href="category.html">Computer Book</a></li>
                <li><a class="nochild " href="category.html">Cookies Books</a></li>
                <li><a class="nochild " href="category.html">English Books</a></li>
                <li><a class="cuuchild " href="category.html">Fashion Books</a> <span class="down"></span>
                  <ul>
                    <li><a class="nochild " href="category.html">test 25</a></li>
                  </ul>
                </li>
                <li><a class="nochild " href="category.html">Games Books</a></li>
                <li><a class="nochild " href="category.html">God Books</a></li>
                <li><a class="nochild " href="category.html">Journal Book</a></li>
                <li><a class="nochild " href="category.html">Knowledge Books</a></li>
                <li><a class="nochild " href="category.html">Magic Books</a></li>
                <li><a class="nochild " href="category.html">Management Books</a></li>
                <li><a class="nochild " href="category.html">Student Books</a></li>
                <li><a class="nochild " href="category.html">Teachers Books</a></li>
                <li><a class="nochild " href="category.html">Toys Books</a></li>
                <li><a class="nochild " href="category.html">Travel Books</a></li>
                <li><a class="nochild " href="category.html">Video Books</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <!--Categories Part End-->
      <!--Latest Product Start-->
     <?php echo $this->blklatest();?>
      <!--Latest Product End-->
      <!--Specials Product Start-->
      <div class="box">
        <div class="box-heading">Specials</div>
        <div class="box-content">
          <div class="box-product">
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/apple_cinema_30-60x60.jpg" alt="Apple Tablet Retina" /></a></div>
              <div class="name"><a href="product.html">Apple Tablet Retina</a></div>
              <div class="price"> <span class="price-old">$119.50</span> <span class="price-new">$107.75</span> </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('42');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/canon_eos_5d_1-60x60.jpg" alt="Canon Digital Camera" /></a></div>
              <div class="name"><a href="product.html">Canon Digital Camera</a></div>
              <div class="price"> <span class="price-old">$119.50</span> <span class="price-new">$96.00</span> </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('30');" class="button" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--Specials Product End-->
    </div>
    <!--Left End-->
    <!--Middle Part Start-->
    <div id="content">
      <p class="welcome">" The clean and modern look allows you to&nbsp; use the theme for every kind of eCommerce online shop. Great Looks on Desktops, Tablets and Mobiles."</p>
      <!--Slideshow Part Start-->
      <div class="slider-wrapper">
        <div id="slideshow" class="nivoSlider"> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/slider-1.jpg" alt="slideshow-1" /></a> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/slider-2.jpg" alt="slideshow-2" /></a> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/slider-3.jpg" alt="slideshow-3" /></a> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/slider-4.jpg" alt="slideshow-4" /></a> </div>
      </div>
      <script type="text/javascript">
$(document).ready(function() {
	$('#slideshow').nivoSlider();
});
</script>
      <!--Slideshow Part End-->
      <!--Featured Product Part Start-->
      <div class="box">
        <div class="box-heading">Featured</div>
        <div class="box-content">
          <div class="box-product">
            <div>
              <div class="image"><a href="#"><img src="<?php echo $this->ImageURL;?>/product/iphone_1-152x152.jpg" alt="iPhone" /></a></div>
              <div class="name"><a href="http://localhost/fullscreen/index.php?route=product/product&amp;product_id=40">iPhone</a></div>
              <div class="price"> $120.68 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('40');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/samsung_tab_1-152x152.jpg" alt="Chair Swing" /></a></div>
              <div class="name"><a href="product.html">Chair Swing</a></div>
              <div class="price"> $236.99 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-3.png" alt="Based on 1 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('49');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/hp_1-152x152.jpg" alt="Casual Saddle Shoes" /></a></div>
              <div class="name"><a href="product.html">Casual Saddle Shoes</a></div>
              <div class="price"> $119.50 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('47');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/bag-152x152.jpg" alt="Bag Lady" /></a></div>
              <div class="name"><a href="product.html">Bag Lady</a></div>
              <div class="price"> $119.50 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('35');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/ipod_touch_1-152x152.jpg" alt="Eyewear Eyeglasses" /></a></div>
              <div class="name"><a href="product.html">Eyewear Eyeglasses</a></div>
              <div class="price"> $119.50 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-3.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('32');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/ipod_shuffle_1-152x152.jpg" alt="Nail Polish" /></a></div>
              <div class="name"><a href="product.html">Nail Polish</a></div>
              <div class="price"> $119.50 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('34');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/samsung_syncmaster_941bw-152x152.jpg" alt="Sports Watch Band" /></a></div>
              <div class="name"><a href="product.html">Sports Watch Band</a></div>
              <div class="price"> $237.00 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-1.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('33');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/macbook_air_1-152x152.jpg" alt="T-shirt Grill" /></a></div>
              <div class="name"><a href="product.html">T-shirt Grill</a></div>
              <div class="price"> $1,177.00 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-5.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('44');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/ipod_classic_1-152x152.jpg" alt="iPad Classic" /></a></div>
              <div class="name"><a href="product.html">iPad Classic</a></div>
              <div class="price"> $119.50 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-0.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('48');" class="button" />
              </div>
            </div>
            <div>
              <div class="image"><a href="product.html"><img src="<?php echo $this->ImageURL;?>/product/macbook_1-152x152.jpg" alt="Fancy Saddle" /></a></div>
              <div class="name"><a href="product.html">Fancy Saddle</a></div>
              <div class="price"> $589.50 </div>
              <div class="rating"><img src="<?php echo $this->ImageURL;?>/stars-2.png" alt="Based on 0 reviews." /></div>
              <div class="cart">
                <input type="button" value="Add to Cart" onClick="addToCart('43');" class="button" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--Featured Product Part End-->
    </div>
    <!--Middle Part End-->
    <div class="clear"></div>
    
  </div>
</div>
<!--Footer Part Start-->
<?php echo $this->render('html/footer.php');?>
<!--Footer Part End-->
</body>

<!-- Mirrored from demo.harnishdesign.net/html/bigshop/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 13 Aug 2015 08:26:01 GMT -->
</html>