<?php 
   
    //------------------------MESSAGES ERROR----------------------
    //$errors = '';
    if(count($this->messageError)>0){
        @$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
    }
    echo $errors;
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


        
                        <div class="clr"></div>
               
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                        
                            <div id="adminfieldset">
                                <div class="adminheader">Detail</div>
                                        
                                        Username : <?php echo $this->formText('user_name','');?>
                                        <br></br>
                                        Password : <?php echo $this->formPassword('password','');?>
                                        <br></br>
                                        <?php echo $this->formSubmit('submit','Dang Nhap');?>
                                </div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>