<?php 
   
    //------------------------MESSAGES ERROR----------------------
    $errors = '';
    if(count($this->messageError)>0){
        $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
    }
	
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


        
                        <div class="clr"></div>
               
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                        
                            <div id="adminfieldset">
                                <div class="adminheader">Detail</div>
                                        <?php echo $errors?>
                                        <?php echo $this->Notes;?>
                                </div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>