<?php echo $this->doctype()?>    
<head>
       <?php echo $this->headTitle()?>
       <?php echo $this->headMeta()?>

        <?php echo $this->headLink()?>

        <?php echo $this->headScript()?>
        
    </head>
    <body id="minwidth-body">
    <?php //echo $this->ImageURL?>
      <?php echo $this->render('html/header.php')?>
        <div id="content-box">
            <div class="border">
                <div class="padding">
                    
                    
                    <?php echo $this->layout()->content;    // Gọi các view của controller vào để hiển thị trên bố cục này ?>
                    

                    <div class="clr"></div>
                </div>
                <div class="clr"></div>
            </div>
        </div>
        <?php echo $this->render('html/footer.php');?>
    </body>
</html> 
