<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Home</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-5" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->CssURL?>/style.css" />
</head>

<body>
	<div id="header">
		<img src="<?php echo $this->ImageURL?>/logo.gif" alt="" width="239" height="71" />
		<div class="lang">
			<strong>Choose language :</strong><br />
			<a href="#"><img src="<?php echo $this->ImageURL?>/lang1.gif" alt="" width="20" height="13" /></a>
			<a href="#"><img src="<?php echo $this->ImageURL?>/lang2.gif" alt="" width="20" height="13" class="center" /></a>
			<a href="#"><img src="<?php echo $this->ImageURL?>/lang3.gif" alt="" width="20" height="13" /></a>
		</div>	
		<div class="cur">
			<strong>Currencies :</strong>
			<select>
				<option>US Dollar</option>
				<option>US Dollar</option>
				<option>US Dollar</option>
			</select>
		</div>
		<div class="cart">
			<strong>Shopping Cart</strong><br /> <span>now in your cart <font>0 items</font></span>
		</div>
	</div>
	<ul id="menu">
		<li><a href="#"><img src="<?php echo $this->ImageURL?>/but1.gif" alt="" width="149" height="60" /></a></li>
		<li><a href="#"><img src="<?php echo $this->ImageURL?>/but2.gif" alt="" width="149" height="60" /></a></li>
		<li><a href="#"><img src="<?php echo $this->ImageURL?>/but3.gif" alt="" width="149" height="60" /></a></li>
		<li><a href="#"><img src="<?php echo $this->ImageURL?>/but4.gif" alt="" width="149" height="60" /></a></li>
		<li><a href="#"><img src="<?php echo $this->ImageURL?>/but5.gif" alt="" width="149" height="60" /></a></li>
	</ul>
	<div id="content"><div class="inner_copy"><a href="http://www.site2you.com/">Website Builder</a> <a href="http://www.freetemplatesonline.com/">fto</a> <a href="http://www.websitetemplates.org/">websitetemplates.org</a> <a href="http://www.webdesign.org/website-design">Website Design</a></div>
		<div id="left">
			<h2>BROWSE BY CATEGORIES :</h2>
			<ul class="leftnav">
				<li><a href="#">Toys on Sale</a></li>
				<li><a href="#">Toys by Age</a></li>
				<li><a href="#">Arts,Crafts &amp; Music</a></li>
				<li><a href="#">Bath Toys</a></li>
				<li><a href="#">Classic &amp; Retro</a></li>
				<li><a href="#">Games</a></li>
				<li><a href="#">Animals &amp; Wildlife</a></li>
				<li><a href="#">Building Blocks</a></li>
				<li><a href="#">Kids Furniture</a></li>
				<li><a href="#">Imaginative Play</a></li>
				<li><a href="#">By Manufacturer</a></li>
				<li><a href="#">Party Favors</a></li>
				<li><a href="#">Wooden Toys</a></li>
				<li><a href="#">Watches &amp; Clocks</a></li>
				<li><a href="#">Silly Stuff</a></li>
				<li><a href="#">Science</a></li>
				<li class="bord"><a href="#">Puzzles</a></li>
			</ul>
			<div class="block1">
				<a href="#">click here</a>
			</div>
		</div>
		<div id="right">
			<div class="block2">
				<a href="#">click here</a>
			</div>
			<div class="block3">
				<a href="#">click here</a>
			</div>
			<div class="items">
				<div class="item">
					<h3>LOREM IPSUM DOLOR</h3>
					<img src="<?php echo $this->ImageURL?>/item1.jpg" alt="" width="85" height="148" />
					<p>
						Lorem ipsum dolor amet wisi enim. 
						<span>$ 14,00</span>
						<a href="#" class="red">Details</a>
						<a href="#">Add to cart</a>
					</p>
				</div>
				<div class="item">
					<h3>IPSUM DOLOR</h3>
					<img src="<?php echo $this->ImageURL?>/item2.jpg" alt="" width="85" height="148" />
					<p>
						Ipsum dolor amet wisi enim minim. 
						<span>$ 15,00</span>
						<a href="#" class="red">Details</a>
						<a href="#">Add to cart</a>
					</p>
				</div>
				<div class="item">
					<h3>AMET WISI ENIM</h3>
					<img src="<?php echo $this->ImageURL?>/item3.jpg" alt="" width="85" height="148" />
					<p>
						Amet wisi enim minim veniam quis. 
						<span>$ 16,00</span>
						<a href="#" class="red">Details</a>
						<a href="#">Add to cart</a>
					</p>
				</div>
				<div class="item">
					<h3>DOLOR AMET WISI</h3>
					<img src="<?php echo $this->ImageURL?>/item4.jpg" alt="" width="85" height="148" />
					<p>
						Dolor amet wisi enim ad minim.
						<span>$ 28,00</span>
						<a href="#" class="red">Details</a>
						<a href="#">Add to cart</a>
					</p>
				</div>
			</div>
			<div class="news">
				<p>
					<span>31.06.2007</span>   <strong>Quis nostrud exerci,</strong> tation ullamcorper suscipit lobortis, nisl ut aliquip.
					<a href="#"><img src="<?php echo $this->ImageURL?>/arrows2.gif" alt="" width="11" height="5" /></a>
				</p>
				<p>
					<span>31.06.2007</span>   <strong>Duis autem</strong> vel eum iriure dolor in hen- drerit in vulputate velit esse molestie consequat.
					<a href="#"><img src="<?php echo $this->ImageURL?>/arrows2.gif" alt="" width="11" height="5" /></a>
				</p>
				<p> <a href="#" class="read">read more</a></p>
			</div>
			<div class="new">
				<img src="<?php echo $this->ImageURL?>/title2.gif" alt="" width="173" height="41" />
				<img src="<?php echo $this->ImageURL?>/pic4.jpg" alt="" width="173" height="113" />
				Veniam quis nostrud exerci. 
				<span>$ 22,00</span>
			</div>
		</div>
	</div>
	<div id="footer">
		<div class="pay">
			<a href="#"><img src="<?php echo $this->ImageURL?>/small1.jpg" alt="" width="80" height="26" /></a>
			<a href="#"><img src="<?php echo $this->ImageURL?>/small2.jpg" alt="" width="39" height="26" /></a>
			<a href="#"><img src="<?php echo $this->ImageURL?>/small3.jpg" alt="" width="39" height="26" /></a>
		</div>
		<div class="copy">
			<ul class="botmenu">
				<li><a href="#">Specials</a></li>
				<li><a href="#">Search</a></li>
				<li><a href="#">Contact Us</a></li>
				<li><a href="#">Create an account </a></li>
				<li class="back"><a href="#">Customer Login</a></li>
			</ul>
			<p>Copyright &copy; 2007 Your Store / <a href="#">Privacy Notice</a> / <a href="#">Terms of Use</a> / <br /><a href="http://www.webdesign.org" class="under">Web Design</a> by <a href="http://www.freetemplatesonline.com" class="under">Free Templates</a> Online</p>
		</div>
	</div>
</body>
</html>
