<?php
/*echo 'This is view of Paginator';
echo $this->currentUrl;*/

	$linkStart 		= $this->currentUrl . '/page/' . $this->first;
	
	$linkPrevious = '#';
	if(isset($this->previous)){
	    $linkPrevious 	= $this->currentUrl . '/page/' . $this->previous;
	}
	$linkNext = '#';
	if(isset($this->next)){
	    $linkNext 		= $this->currentUrl . '/page/' . $this->next;
	}
	
	$linkEnd 		= $this->currentUrl . '/page/' . $this->last;
	
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		if($this->current == $key){
			$strPage .= '<b>' . $key .'</b>';
		}else{
			$linkPage = $this->currentUrl . '/page/' . $key;
			$strPage .= '<a href="' . $linkPage . '">' . $key .'</a>'; 
		}
	}

	$page = 'Page ' . $this->current .' Of ' . $this->last;
?>

<div class="pagination">
          <div class="links">
            <a href="<?php echo $linkStart;?>" title="Start">Start</a>
          </div>
          <div class="links">
            <a href="<?php echo $linkPrevious;?>" title="Prev">Previous</a>
          </div>
        <div class="links">
        <?php echo $strPage;?>
         </div>
          <div class="links">
            <a href="<?php echo $linkNext;?>" title="Next">Next</a>
          </div>
          <div class="links">
            <a href="<?php echo $linkEnd;?>" title="End">End</a>
          </div>
       <!--  <div class="results">Showing 1 to 15 of 16 (2 Pages)</div> -->
</div>