<?php
echo $this->form;
?>

<style type="text/css">
#row{
	
}
#row .label{
	width: 150px;
	padding: 5px;
	border-bottom: solid 1px #E9E9E9;
	border-right: solid 1px #E9E9E9;
	background-color: #F6F6F6;
	text-align: right;
	font-weight:  bold;
	float: left;
}

#row .view-helper{
	margin-left: 165px;
}

#row .errors{
	padding: 0px;
	margin: 0px;
	list-style-position: inside;
	color: red;
	list-style-type: none;
}

#row .div-description{
	color: #999;
	font-style: italic;
}

</style>
<div id="row">
	<div class="label">
		<label for="textbox">Text box:*:</label>
	</div>
	<div class="view-helper">
		<input type="text" class="txtmedium" helper="formText" value="" id="textbox" name="textbox">
		<div class="div-error">
			<ul class="errors">
				<li>Value is required and can't be empty</li>
			</ul>
		</div>
		<br>
		<span class="div-description">Hien thi o textbox bang Zend Form</span>
	</div>
	<div class="clr"></div>
</div>