<div id="content">
      <p class="welcome">Welcome to Shop Sport, Your choice is define you</p>
      <!--Slideshow Part Start-->
      <div class="slider-wrapper">
        <div id="slideshow" class="nivoSlider"> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/banner2.png" alt="slideshow-1" /></a> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/banner3.png" alt="slideshow-2" /></a> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/banner4.png" alt="slideshow-3" /></a> <a href="#"><img src="<?php echo $this->ImageURL;?>/slider/banner5.png" alt="slideshow-4" /></a> </div>
      </div>
      <script type="text/javascript">
$(document).ready(function() {
	$('#slideshow').nivoSlider();
});
</script>
      <!--Slideshow Part End-->
      <!--Featured Product Part Start-->
      <?php echo $this->blkfeatured();?>                                        
      <!--Featured Product Part End-->
    </div>                                              