<?php 
	
?>
<form name="appForm" method="post" action="">

        <?php echo $this->render('admin-category/toolbar/delete.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('admin-category/submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->

<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div class="error">
								    Do you agree to delete this Item
								</div>
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>