<?php 
   
///////// OLD
	/* $group_name = $this->formText('group_name','',array('class'=>'txtmedium'));
	$avatar = $this->formFile('avatar',array('style'=>'width: 250px'));
	$ranking = $this->formFile('ranking',array('style'=>'width: 250px'));
	$options = array('No','Yes');
	$group_acp = $this->formRadio('group_acp',0,null,$options, ' ');
	$group_default = $this->formRadio('group_default',0,null,$options, ' ');
	$options = array('Inactive','Active');
	$status = $this->formRadio('status',0,null,$options, ' ');
	$order = $this->formText('order',10,array('class'=>'txtshort')); */
	
    //-------------------INPUT ELEMENTS----------------
    
    // id,name,status,parent,order,created,created_by
    $namecate		= $this->formText('name',$this->Items['name'],array('class'=>'txtmedium'));
    
    $options		= array('Inactive','Active');   
    $status			= $this->formRadio('status','',null,$options, ' ');
    $picture 	    = $this->formFile('picture');
    $order	        = $this->formText('order',$this->Items['order'],array('class'=>'txtsort'));
    $parents 		= $this->cmsSelect('parents',$this->Items['parents'],
										$this->slbCategory,array('size'=>10,'style'=>'min-width: 200px;'));
        
    $arrInput = array(
        array('label'=>'Category Name: ', 'input'=>$namecate),
        array('label'=>'Status: ', 'input'=>$status),
        array('label'=>'Picture: ', 'input'=>$picture),
        array('label'=>'Order: ', 'input'=>$order),
        array('label'=>'Parent: ', 'input'=>$parents),
       
    );
    //------------------------MESSAGES ERROR----------------------
    $errors = '';
    if(count($this->messageError)>0){
        $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
    }
	
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


        <?php echo $this->render('admin-category/toolbar/edit.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('admin-category/submenu/index.php') ?>
                <?php echo $errors?>
                
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                        
                            <div id="adminfieldset">
                                <div class="adminheader">Detail</div>
                             
								<?php echo $this->partialLoop('rowadd.php',$arrInput);?>
                                
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>