<?php //$linkInfo = $this->baseUrl($this->currentControlle.'/info/id/'.$id)
    
    
    $ssfilter = $this->arrParam['sessionfilter'];
    echo '<pre>';
    print_r($ssfilter);
    echo '</pre>'; 
    
    // Phan sap xep cua cac nhan
    $actionLink = $this->baseUrl($this->currentControlle.'/filter/type/order');
    
    
    // Key sau khi tim kiem, neu khong co se rong
    $keyaftersearch = $ssfilter['searchbox'];
    $keysearch  = $this->formText('searchbox',$keyaftersearch,array('class'=>'txtsearch'));

    // Tìm Kiếm
    $linksearch = $this->baseUrl($this->currentControlle.'/filter/type/search/key/1');
    $btnsearch  = $this->formButton('search-button','Tìm Kiếm',array('onclick'=>"OnSubmitForm('". $linksearch ."')"));
    
    // Xóa Tìm kiếm
    $linkclearsearch = $this->baseUrl($this->currentControlle.'/filter/type/search/key/0');
    $btnclearsearch  = $this->formButton('clear-button','Xóa tìm kiếm',array('onclick'=>"OnSubmitForm('". $linkclearsearch ."')"));
 
   
    
?>
<form name="appForm" method="post" action="">

        <?php echo $this->render('admin-category/toolbar/index.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('admin-category/submenu/index.php') ?>
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                                <div id="search">
                                    <div style="float:left">
                                        <?php echo $keysearch . ' ' . $btnsearch . ' ' .$btnclearsearch;?>
                                    </div>
                                    <div style="float:right">
                                        
                                    </div>
                                      <div class="clr"></div>
                                </div>
                                
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()"></th>
                                            <th>
                                                <a href="#">Category Name</a>
                                                
                                            </th>
                                            <th width="89">Status</th>
                                            <th width="83">Parent</th>
                                            <th width="86">Order</th>						
                                            <th width="77">Created_By</th>
                                            <th width="90">ConTrol</th>

                                            <th width="34">ID</th>
                                        </tr>
                                    </thead>
                                    
                                    <?php 
                                    if (count($this->Items > 0)){
                                    foreach ($this->Items as $key=>$value){
                                        $id        = $value['id'];
                                        $namecate  = $value['name'];
                                        if($value['level'] == 1){
                                            $namecate = '<strong>+'.$namecate.'</strong>';
                                        }else{
                                            $padding  = ($value['level'] - 1) * 25;
                                            $padding = 'padding-left: ' . $padding . 'px;';
                                            $namecate = '<div style="' . $padding . '">- ' . $value['name'] . '</div>';
                                        }
                                        $status    = $value['status'];
                                        $parents     = $value['parents'];
                                        $order     = $this->formText('order['.$value['id'].']',$value['order'],array('style'=>'width: 30px; text-align: center;'));
                                        $created   = $value['created'];
                                        $created_by   = $value['user_name'];
                                      
                                        if ($status == 1){
                                            $linkstatus =  $this->baseUrl($this->currentControlle.'/status/type/0/id/'.$id);
                                            $status = '<img src="'.$this->ImageURL.'/icon/active.png">';
                                        }else{
                                            $linkstatus =  $this->baseUrl($this->currentControlle.'/status/type/1/id/'.$id);
                                            $status = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
                                        }
                                       /*  if ($groupacp == 1){
                                            $linkgroupacp =  $this->baseUrl($this->currentControlle.'/status/type/0/idacp/'.$id);
                                            $groupacp = '<img src="'.$this->ImageURL.'/icon/active.png">';
                                        }else{
                                            $linkgroupacp =  $this->baseUrl($this->currentControlle.'/status/type/1/idacp/'.$id);
                                            $groupacp = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
                                        } */
                                        $linkinfogroup      = $this->baseUrl($this->currentControlle.'/info/id/'.$id);
                                        $linkEditGroup      = $this->baseUrl($this->currentControlle.'/edit/id/'.$id);
                                        $linkDeleteGroup    = $this->baseUrl($this->currentControlle.'/delete/id/'.$id);
                                        $checkbox           = $this->formCheckbox('cid[]',$id);
                  
                                        
                                    ?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $checkbox;?></td>
                                        <td align="left"><?php  echo $namecate;?></td>
                                        <td align="center">
                                            <a href="<?php echo $linkstatus;?>">
                                        	   <?php echo $status;?>
                                            </a>
                                        </td>
                                        <td align="center">
                                            <?php echo $parents;?>
                                        </td>
                                        
                                        <td align="center">
                                        <?php echo $order?>
                                        </td>

                                        <td align="center"><?php echo $created_by;?></td>
                                        <td align="center">
                                        <a href="<?php echo $linkinfogroup;?>">
                                        	<img src="<?php echo $this->ImageURL?>/icon_info.png" title="View Info"> 
                                        </a>
                                        <a href="<?php echo $linkEditGroup;?>">
                                            <img src="<?php echo $this->ImageURL?>/icon_edit.png" title="Edit Group"> 
                                        </a>
                                        <a href="<?php echo $linkDeleteGroup;?>">
                                            <img src="<?php echo $this->ImageURL?>/icon_del.png" title="Delete Group"> 
                                         </a></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
                                            }
                                        }   
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                       <?php 
                                                         /*  $currentUrl = $this->baseUrl($this->currentControlle . '/index');
                                                          echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); */
                                                       ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>