<?php 
   
///////// OLD
	/* $group_name = $this->formText('group_name','',array('class'=>'txtmedium'));
	$avatar = $this->formFile('avatar',array('style'=>'width: 250px'));
	$ranking = $this->formFile('ranking',array('style'=>'width: 250px'));
	$options = array('No','Yes');
	$group_acp = $this->formRadio('group_acp',0,null,$options, ' ');
	$group_default = $this->formRadio('group_default',0,null,$options, ' ');
	$options = array('Inactive','Active');
	$status = $this->formRadio('status',0,null,$options, ' ');
	$order = $this->formText('order',10,array('class'=>'txtshort')); */
	
    //-------------------INPUT ELEMENTS----------------
    
    // id,name,status,parent,order,created,created_by
    $namecate		= $this->Items['name'];
    if(!empty($this->Items['picture'])){
        $catepicture	= FILE_URL.'/users/img100x100/'.$this->Items['picture'];
        $catepicture    = '<img src="'.$catepicture.'"> <br>'.$this->Items['picture'];
    }
    $status			= $this->Items['status'];
    if ($status == 1){
        $status = '<img src="'.$this->ImageURL.'/icon/active.png">';
    }else{
        $status = '<img src="'.$this->ImageURL.'/icon/inactive.png">';
    }
    //echo $status;
    $order	        = $this->Items['order'];
    $parents 		= $this->Items['parents'];
        
    $arrInput = array(
        array('label'=>'Category Name: ', 'input'=>$namecate),
        array('label'=>'Status: ', 'input'=>$status),
        array('label'=>'Order: ', 'input'=>$order),
        array('label'=>'Parent: ', 'input'=>$parents),
       
    );
    //------------------------MESSAGES ERROR----------------------
   /*  $errors = '';
    if(count($this->messageError)>0){
        $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
    } */
	
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


        <?php echo $this->render('admin-category/toolbar/info.php') ?>
                        <div class="clr"></div>
                      
                <?php echo $this->render('admin-category/submenu/index.php') ?>
                <?php // echo $errors?>
                
        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
                        
                            <div id="adminfieldset">
                                <div class="adminheader">Detail</div>
                             
								<?php echo $this->partialLoop('rowadd.php',$arrInput);?>
                                
							</div>

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>